server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://121.36.242.160:54321/tjtelemed
    username: db01
    password: tjrcs
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.tj.webris

